name: Auto Update

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly
  workflow_dispatch:
  push:
    paths-ignore: [README.md, .gitignore]

jobs:
  check-version:
    runs-on: ubuntu-latest

    outputs:
      should_build: ${{ steps.compare-versions.outputs.should_build }}
      version: ${{ steps.tailscale-release.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest Tailscale release
        id: tailscale-release
        run: |
          latest=$(curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r .tag_name)
          echo "version=${latest#v}" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        env:
          version: ${{ steps.tailscale-release.outputs.version }}
        run: |
          repo_version=$(git describe --tags --abbrev=0 || echo "none")
          if [[ "$repo_version" != "v${version}" ]]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: [check-version]
    if: |
      needs.check-version.outputs.should_build == 'true'
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.check-version.outputs.version }}
